### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by joeyparrish** [joeyparrish/letterboxed#1]
I forked this from @SivanMehta, but there was no license information anywhere in the repo.  I need to clarify the license of the original code, so that I can continue this forked version under compatible terms.

@SivanMehta, can you please help me by clarifying the license terms of your letterboxed repo?  I would have filed this issue against your repo, but the issues tab is turned off.

If you don't have strong opinions about open source licenses, I generally choose either:
 - GPL (v2 or v3) if I want the code to remain open forever
 - Apache (v2) if I want to permit people to incorporate the code in closed source applications

https://choosealicense.com/ also has some simple guidance that you may find useful.

Thanks!

**Comment by SivanMehta** [comment]
@joeyparrish I've added the [GPL](https://choosealicense.com/licenses/gpl-3.0/#) license

**Comment by joeyparrish** [comment]
Wonderful!  Thank you so much.
